### ISSUE TITLE
Ivy dependency issue

### ISSUE THREAD

**Issue by bodgergely** [bitsofproof/supernode#2]
I am getting the below message when trying to retrieve the dependencies.

Buildfile: D:\IT\GitHub\supernode\build.xml
retrieve:
No ivy:settings found for the default reference 'ivy.instance'.  A default instance will be used
[ivy:resolve] :: Ivy 2.0.0-beta1 - 20071206070608 :: http://ant.apache.org/ivy/ ::
:: loading settings :: file = D:\IT\GitHub\supernode\ivysettings.xml
[ivy:resolve] :: resolving dependencies :: com.bitsofproof#server;working@TylerPC
[ivy:resolve]   confs: [default]
[ivy:resolve]   found org.springframework#spring-context;3.1.2.RELEASE in central
[ivy:resolve]   found org.springframework#spring-aop;3.1.2.RELEASE in central
[ivy:resolve]   found aopalliance#aopalliance;1.0 in central
[ivy:resolve]   found org.springframework#spring-asm;3.1.2.RELEASE in central
[ivy:resolve]   found org.springframework#spring-beans;3.1.2.RELEASE in central
[ivy:resolve]   found org.springframework#spring-core;3.1.2.RELEASE in central
[ivy:resolve]   found org.springframework#spring-expression;3.1.2.RELEASE in central
[ivy:resolve]   found org.hamcrest#hamcrest-all;1.1 in central
[ivy:resolve]   found org.codehaus.jsr166-mirror#jsr166;1.7.0 in central
[ivy:resolve]   found backport-util-concurrent#backport-util-concurrent;3.0 in central
[ivy:resolve]   found javax.annotation#jsr250-api;1.0 in central
[ivy:resolve]   found org.apache.geronimo.specs#geronimo-ejb_3.0_spec;1.0.1 in central
[ivy:resolve]   found org.apache.geronimo.specs#geronimo-interceptor_3.0_spec;1.0.1 in central
[ivy:resolve]   found javax.inject#javax.inject;1 in central
[ivy:resolve]   found org.apache.geronimo.specs#geronimo-jms_1.1_spec;1.1 in central
[ivy:resolve]   found javax.validation#validation-api;1.0.0.GA in central
[ivy:resolve]   found javax.xml.ws#jaxws-api;2.1-1 in central
[ivy:resolve]   found javax.xml.bind#jaxb-api;2.1 in central
[ivy:resolve]   found javax.xml.stream#stax-api;1.0-2 in central
[ivy:resolve]   found javax.activation#activation;1.1 in central
[ivy:resolve]   found javax.xml.soap#saaj-api;1.3 in central
[ivy:resolve] activation#activation;1.0.2 is relocated to javax.activation#activation;1.0.2. Please update your dependencies.
[ivy:resolve]   found activation#activation;1.0.2 in central
[ivy:resolve]   found javax.jws#jsr181;1.0 in central
[ivy:resolve]   found cglib#cglib-nodep;2.2 in central
[ivy:resolve]   found org.aspectj#aspectjweaver;1.6.8 in central
[ivy:resolve]   found org.beanshell#bsh;2.0b4 in central
[ivy:resolve]   found org.codehaus.groovy#groovy-all;1.6.3 in central
[ivy:resolve]   found junit#junit;3.8.2 in central
[ivy:resolve]   found org.apache.ant#ant;1.7.1 in central
[ivy:resolve]   found org.apache.ant#ant-launcher;1.7.1 in central
[ivy:resolve]   found jline#jline;0.9.94 in central
[ivy:resolve]   found org.jruby#jruby;1.4.0 in central
[ivy:resolve]   found asm#asm;3.0 in central
[ivy:resolve]   found joda-time#joda-time;1.6 in central
[ivy:resolve]   found org.springframework#spring-instrument;3.1.2.RELEASE in central
[ivy:resolve]   found org.apache.geronimo.specs#geronimo-jta_1.1_spec;1.1 in central
[ivy:resolve]   found net.sf.ehcache#ehcache-core;2.0.0 in central
[ivy:resolve]   found org.slf4j#slf4j-api;1.5.8 in central
[ivy:resolve]   found org.hibernate#hibernate-validator;4.3.0.Final in central
[ivy:resolve]   found org.jboss.logging#jboss-logging;3.1.0.CR2 in central
[ivy:resolve]   found org.hibernate.javax.persistence#hibernate-jpa-2.0-api;1.0.1.Final in central
[ivy:resolve]   found org.jsoup#jsoup;1.6.1 in central
[ivy:resolve]   found org.springframework.data#spring-data-jpa;1.1.0.RELEASE in central
[ivy:resolve]   found org.springframework.data#spring-data-commons-core;1.3.0.RELEASE in central
[ivy:resolve]   found junit#junit-dep;4.8.2 in central
[ivy:resolve]   found org.hamcrest#hamcrest-core;1.1 in central
[ivy:resolve]   found org.slf4j#slf4j-api;1.6.1 in central
[ivy:resolve]   found org.aspectj#aspectjrt;1.6.12 in central
[ivy:resolve]   found org.slf4j#jcl-over-slf4j;1.6.1 in central
[ivy:resolve]   found com.mysema.querydsl#querydsl-apt;2.5.0 in central
[ivy:resolve]   found javax.jdo#jdo2-api;2.3-eb in central
[ivy:resolve]   found javax.transaction#transaction-api;1.1 in central
[ivy:resolve]   found org.hibernate#hibernate-entitymanager;3.6.9.Final in central
[ivy:resolve]   found org.hibernate#hibernate-core;3.6.9.Final in central
[ivy:resolve]   found org.apache.openjpa#openjpa-persistence-jdbc;2.2.0 in central
[ivy:resolve]   found org.apache.openjpa#openjpa-jdbc;2.2.0 in central
[ivy:resolve]   found org.apache.openjpa#openjpa-kernel;2.2.0 in central
[ivy:resolve]   found org.apache.openjpa#openjpa-lib;2.2.0 in central
[ivy:resolve]   found commons-lang#commons-lang;2.4 in central
[ivy:resolve]   found commons-collections#commons-collections;3.2.1 in central
[ivy:resolve]   found net.sourceforge.serp#serp;1.13.1 in central
[ivy:resolve]   found org.apache.geronimo.specs#geronimo-jms_1.1_spec;1.1.1 in central
[ivy:resolve]   found org.apache.geronimo.specs#geronimo-jta_1.1_spec;1.1.1 in central
[ivy:resolve]   found commons-pool#commons-pool;1.5.4 in central
[ivy:resolve]   found asm#asm;3.2 in central
[ivy:resolve]   found org.apache.openjpa#openjpa-persistence;2.2.0 in central
[ivy:resolve]   found org.apache.geronimo.specs#geronimo-jpa_2.0_spec;1.1 in central
[ivy:resolve]   found com.mysema.querydsl#querydsl-jpa;2.5.0 in central
[ivy:resolve]   found org.slf4j#slf4j-log4j12;1.6.1 in central
[ivy:resolve]   found log4j#log4j;1.2.16 in central
[ivy:resolve]   found javax.enterprise#cdi-api;1.0 in central
[ivy:resolve]   found org.jboss.interceptor#jboss-interceptor-api;1.1 in central
[ivy:resolve]   found org.apache.derby#derbyclient;10.9.1.0 in central
[ivy:resolve]   found org.slf4j#slf4j-log4j12;1.6.6 in central
[ivy:resolve]   found org.slf4j#slf4j-api;1.6.6 in central
[ivy:resolve]   found log4j#log4j;1.2.17 in central
[ivy:resolve]   found org.bouncycastle#bcprov-jdk15on;1.47 in central
[ivy:resolve]   found commons-cli#commons-cli;1.2 in central
[ivy:resolve] :: resolution report :: resolve 28230ms :: artifacts dl 770ms
[ivy:resolve]   :: evicted modules:
[ivy:resolve]   org.springframework#spring-core;[3.0.7.RELEASE, 4.0.0.RELEASE) by [org.springframework#spring-core;3.1.2.RELEASE] in [default]
[ivy:resolve]   org.hibernate.javax.persistence#hibernate-jpa-2.0-api;1.0.0.Final by [org.hibernate.javax.persistence#hibernate-jpa-2.0-api;1.0.1.Final] in [default]
[ivy:resolve]   org.slf4j#slf4j-api;1.5.8 by [org.slf4j#slf4j-api;1.6.1] in [default]
[ivy:resolve]   log4j#log4j;1.2.16 by [log4j#log4j;1.2.17] in [default]
[ivy:resolve]   org.apache.geronimo.specs#geronimo-jms_1.1_spec;1.1 by [org.apache.geronimo.specs#geronimo-jms_1.1_spec;1.1.1] in [default]
[ivy:resolve]   asm#asm;3.0 by [asm#asm;3.2] in [default]
[ivy:resolve]   javax.activation#activation;1.0.2 by [javax.activation#activation;1.1] in [default]
[ivy:resolve]   org.springframework#spring-instrument;[3.0.7.RELEASE, 4.0.0.RELEASE) by [org.springframework#spring-instrument;3.1.2.RELEASE] in [default]
[ivy:resolve]   org.apache.geronimo.specs#geronimo-jta_1.1_spec;1.1 by [org.apache.geronimo.specs#geronimo-jta_1.1_spec;1.1.1] in [default]
[ivy:resolve]   junit#junit;3.8.1 by [junit#junit;3.8.2] in [default]
[ivy:resolve]   org.slf4j#slf4j-api;1.6.1 by [org.slf4j#slf4j-api;1.6.6] in [default]
[ivy:resolve]   org.slf4j#slf4j-log4j12;1.6.1 by [org.slf4j#slf4j-log4j12;1.6.6] in [default]
[ivy:resolve]   org.springframework#spring-beans;[3.0.7.RELEASE, 4.0.0.RELEASE) by [org.springframework#spring-beans;3.1.2.RELEASE] in [default]
    ---------------------------------------------------------------------
    |                  |            modules            ||   artifacts   |
    |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
    ---------------------------------------------------------------------
    |      default     |   89  |   76  |   0   |   13  ||   70  |   0   |
    ---------------------------------------------------------------------
[ivy:resolve] :: problems summary ::
[ivy:resolve] :::: WARNINGS
[ivy:resolve]       module not found: org.springframework#spring-orm;[3.0.7.RELEASE, 4.0.0.RELEASE)
[ivy:resolve]   ==== central: tried
[ivy:resolve]     http://repo1.maven.org/maven2/org/springframework/spring-orm/[3.0.7.RELEASE, 4.0.0.RELEASE)/spring-orm-[3.0.7.RELEASE, 4.0.0.RELEASE).pom
[ivy:resolve]     -- artifact org.springframework#spring-orm;[3.0.7.RELEASE, 4.0.0.RELEASE)!spring-orm.jar:
[ivy:resolve]     http://repo1.maven.org/maven2/org/springframework/spring-orm/[3.0.7.RELEASE, 4.0.0.RELEASE)/spring-orm-[3.0.7.RELEASE, 4.0.0.RELEASE).jar
[ivy:resolve]   ==== springsource: tried
[ivy:resolve]     http://repo.springsource.org/release/org/springframework/spring-orm/[3.0.7.RELEASE, 4.0.0.RELEASE)/spring-orm-[3.0.7.RELEASE, 4.0.0.RELEASE).pom
[ivy:resolve]     -- artifact org.springframework#spring-orm;[3.0.7.RELEASE, 4.0.0.RELEASE)!spring-orm.jar:
[ivy:resolve]     http://repo.springsource.org/release/org/springframework/spring-orm/[3.0.7.RELEASE, 4.0.0.RELEASE)/spring-orm-[3.0.7.RELEASE, 4.0.0.RELEASE).jar
[ivy:resolve]       module not found: org.springframework#spring-tx;[3.0.7.RELEASE, 4.0.0.RELEASE)
[ivy:resolve]   ==== central: tried
[ivy:resolve]     http://repo1.maven.org/maven2/org/springframework/spring-tx/[3.0.7.RELEASE, 4.0.0.RELEASE)/spring-tx-[3.0.7.RELEASE, 4.0.0.RELEASE).pom
[ivy:resolve]     -- artifact org.springframework#spring-tx;[3.0.7.RELEASE, 4.0.0.RELEASE)!spring-tx.jar:
[ivy:resolve]     http://repo1.maven.org/maven2/org/springframework/spring-tx/[3.0.7.RELEASE, 4.0.0.RELEASE)/spring-tx-[3.0.7.RELEASE, 4.0.0.RELEASE).jar
[ivy:resolve]   ==== springsource: tried
[ivy:resolve]     http://repo.springsource.org/release/org/springframework/spring-tx/[3.0.7.RELEASE, 4.0.0.RELEASE)/spring-tx-[3.0.7.RELEASE, 4.0.0.RELEASE).pom
[ivy:resolve]     -- artifact org.springframework#spring-tx;[3.0.7.RELEASE, 4.0.0.RELEASE)!spring-tx.jar:
[ivy:resolve]     http://repo.springsource.org/release/org/springframework/spring-tx/[3.0.7.RELEASE, 4.0.0.RELEASE)/spring-tx-[3.0.7.RELEASE, 4.0.0.RELEASE).jar
[ivy:resolve]       module not found: com.mysema.querydsl#querydsl-codegen;${project.parent.version}
[ivy:resolve]   ==== central: tried
[ivy:resolve]     http://repo1.maven.org/maven2/com/mysema/querydsl/querydsl-codegen/${project.parent.version}/querydsl-codegen-${project.parent.version}.pom
[ivy:resolve]     -- artifact com.mysema.querydsl#querydsl-codegen;${project.parent.version}!querydsl-codegen.jar:
[ivy:resolve]     http://repo1.maven.org/maven2/com/mysema/querydsl/querydsl-codegen/${project.parent.version}/querydsl-codegen-${project.parent.version}.jar
[ivy:resolve]   ==== springsource: tried
[ivy:resolve]     http://repo.springsource.org/release/com/mysema/querydsl/querydsl-codegen/${project.parent.version}/querydsl-codegen-${project.parent.version}.pom
[ivy:resolve]     -- artifact com.mysema.querydsl#querydsl-codegen;${project.parent.version}!querydsl-codegen.jar:
[ivy:resolve]     http://repo.springsource.org/release/com/mysema/querydsl/querydsl-codegen/${project.parent.version}/querydsl-codegen-${project.parent.version}.jar
[ivy:resolve]       module not found: org.springframework#spring-aspects;[3.0.7.RELEASE, 4.0.0.RELEASE)
[ivy:resolve]   ==== central: tried
[ivy:resolve]     http://repo1.maven.org/maven2/org/springframework/spring-aspects/[3.0.7.RELEASE, 4.0.0.RELEASE)/spring-aspects-[3.0.7.RELEASE, 4.0.0.RELEASE).pom
[ivy:resolve]     -- artifact org.springframework#spring-aspects;[3.0.7.RELEASE, 4.0.0.RELEASE)!spring-aspects.jar:
[ivy:resolve]     http://repo1.maven.org/maven2/org/springframework/spring-aspects/[3.0.7.RELEASE, 4.0.0.RELEASE)/spring-aspects-[3.0.7.RELEASE, 4.0.0.RELEASE).jar
[ivy:resolve]   ==== springsource: tried
[ivy:resolve]     http://repo.springsource.org/release/org/springframework/spring-aspects/[3.0.7.RELEASE, 4.0.0.RELEASE)/spring-aspects-[3.0.7.RELEASE, 4.0.0.RELEASE).pom
[ivy:resolve]     -- artifact org.springframework#spring-aspects;[3.0.7.RELEASE, 4.0.0.RELEASE)!spring-aspects.jar:
[ivy:resolve]     http://repo.springsource.org/release/org/springframework/spring-aspects/[3.0.7.RELEASE, 4.0.0.RELEASE)/spring-aspects-[3.0.7.RELEASE, 4.0.0.RELEASE).jar
[ivy:resolve]       module not found: com.mysema.querydsl#querydsl-core;${project.parent.version}
[ivy:resolve]   ==== central: tried
[ivy:resolve]     http://repo1.maven.org/maven2/com/mysema/querydsl/querydsl-core/${project.parent.version}/querydsl-core-${project.parent.version}.pom
[ivy:resolve]     -- artifact com.mysema.querydsl#querydsl-core;${project.parent.version}!querydsl-core.jar:
[ivy:resolve]     http://repo1.maven.org/maven2/com/mysema/querydsl/querydsl-core/${project.parent.version}/querydsl-core-${project.parent.version}.jar
[ivy:resolve]   ==== springsource: tried
[ivy:resolve]     http://repo.springsource.org/release/com/mysema/querydsl/querydsl-core/${project.parent.version}/querydsl-core-${project.parent.version}.pom
[ivy:resolve]     -- artifact com.mysema.querydsl#querydsl-core;${project.parent.version}!querydsl-core.jar:
[ivy:resolve]     http://repo.springsource.org/release/com/mysema/querydsl/querydsl-core/${project.parent.version}/querydsl-core-${project.parent.version}.jar
[ivy:resolve]       [NOT FOUND  ] javax.jws#jsr181;1.0!jsr181.jar (160ms)
[ivy:resolve]   ==== central: tried
[ivy:resolve]     http://repo1.maven.org/maven2/javax/jws/jsr181/1.0/jsr181-1.0.jar
[ivy:resolve]       [NOT FOUND  ] org.apache.geronimo.specs#geronimo-jpa_2.0_spec;1.1!geronimo-jpa_2.0_spec.bundle (360ms)
[ivy:resolve]   ==== central: tried
[ivy:resolve]     http://repo1.maven.org/maven2/org/apache/geronimo/specs/geronimo-jpa_2.0_spec/1.1/geronimo-jpa_2.0_spec-1.1.bundle
[ivy:resolve]       [NOT FOUND  ] log4j#log4j;1.2.17!log4j.bundle (160ms)
[ivy:resolve]   ==== central: tried
[ivy:resolve]     http://repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.bundle
[ivy:resolve]       ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]       ::          UNRESOLVED DEPENDENCIES         ::
[ivy:resolve]       ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]       :: org.springframework#spring-aspects;[3.0.7.RELEASE, 4.0.0.RELEASE): not found
[ivy:resolve]       :: com.mysema.querydsl#querydsl-core;${project.parent.version}: not found
[ivy:resolve]       :: org.springframework#spring-orm;[3.0.7.RELEASE, 4.0.0.RELEASE): not found
[ivy:resolve]       :: com.mysema.querydsl#querydsl-codegen;${project.parent.version}: not found
[ivy:resolve]       :: org.springframework#spring-tx;[3.0.7.RELEASE, 4.0.0.RELEASE): not found
[ivy:resolve]       ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve] 
[ivy:resolve]       ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]       ::              FAILED DOWNLOADS            ::
[ivy:resolve]       :: ^ see resolution messages for details  ^ ::
[ivy:resolve]       ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]       :: javax.jws#jsr181;1.0!jsr181.jar
[ivy:resolve]       :: org.apache.geronimo.specs#geronimo-jpa_2.0_spec;1.1!geronimo-jpa_2.0_spec.bundle
[ivy:resolve]       :: log4j#log4j;1.2.17!log4j.bundle
[ivy:resolve]       ::::::::::::::::::::::::::::::::::::::::::::::

**Comment by bitsofproof** [comment]
added explicit reference to ivysettings.xml into build.xml. 

Let me know if that helped.

**Comment by bitsofproof** [comment]
completely reworked the build. This issue is likely no longer relevant

**Comment by bodgergely** [comment]
Thanks. I was able to build it on my other desktop. Might have been some local environment issue at my side.
