### ISSUE TITLE
Won't build on Java 7.

### ISSUE THREAD

**Issue by marklister** [bitsofproof/supernode#3]
I'm trying to build commit a7483c8c9af46fd9a7ce422cd1fd36e463a01788.  It fails with this error:

`[javac] /home/mark/workspace/supernode/src/com/bitsofproof/supernode/model/PooledDatasource.java:35: error: PooledDatasource is not abstract and does not override abstract method getParentLogger() in CommonDataSource
    [javac] public class PooledDatasource implements DataSource
    [javac]        ^
    [javac] 1 error`

My javac:

`mark@Hannibal:~/workspace/supernode$ java -version
java version "1.7.0_09"
OpenJDK Runtime Environment (IcedTea7 2.3.3) (7u9-2.3.3-0ubuntu1~12.10.1)
OpenJDK Server VM (build 23.2-b09, mixed mode)`

I checked out (approx) HEAD~40 and that built Ok...

You might consider using [Travis ci](https://travis-ci.org/) or something similar.

**Comment by bitsofproof** [comment]
This rather looks like a java 6 vs java 7 problem. I build using java 6.

**Comment by marklister** [comment]
Yeah, as [this question on SO](http://stackoverflow.com/questions/8503338/new-method-added-in-javax-sql-commondatasource-in-1-7) suggests.  You might want to update the build instructions.
