### ISSUE TITLE
problem with Maven

### ISSUE THREAD

**Issue by BlueMeanie** [bitsofproof/supernode#39]
getting this when I run 'mvn package'

**Component descriptor role: 'com.jcraft.jsch.UIKeyboardInteractive', implementation: 'org.apache.maven.wagon.providers.ssh.jsch.interactive.PrompterUIKeyboardInteractive', role hint: 'default' has a hint, but there are other implementations that don't**

**Comment by bitsofproof** [comment]
I am not aware of any use of the class in the message. My guess is that there is some local installation of the ssh package. Try removing the <extensions>
                        <extension>
                                <groupId>org.apache.maven.wagon</groupId>
                                <artifactId>wagon-ssh</artifactId>
                                <version>2.4</version>
                        </extension>
                </extensions>

from the pom
