### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by manpages** [bitsofproof/supernode#45]
Please consider mentioning `bop-service.sh` in README.md.
Also please add information that supernode builds against protoc --version #=> 2.5.0 simply by replacing (in pom.xml)

```
                <protobuf.version>2.4.1</protobuf.version>
```

with

```
                <protobuf.version>2.5.0</protobuf.version>
```

This is required to properly build supernode on rolling-release Linux distros.

**Comment by bitsofproof** [comment]
I use Travis for continous integration tests, that uses ubuntu LTS which is still on 2.4.1. This is why I did not upgrade yet.
